Vagrant.configure("2") do |config|
  $prefix_ip="192.168.10."
  $master_ip_start = 3
 
  config.vm.define "k8s-master" do |master|
      master.vm.box = "base-k8s-ubuntu"
      master.vm.network "private_network", ip: "#{$prefix_ip}#{$master_ip_start}"
      master.vm.provision "shell", path: "../up_sh/init_environment.sh"
      master.vm.provision "shell", path: "../up_sh/init_k8s.sh", args:["#{$prefix_ip}#{$master_ip_start}"]
      master.vm.provision "shell", path: "../up_sh/master_install.sh"
      master.vm.hostname = "k8s-master"
      master.vm.provider "virtualbox" do |v|
         v.name = "k8s-master"
         v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
      end
  end
end