Vagrant.configure("2") do |config|
  
   config.vm.define "base-k8s-ubuntu" do |k8s|
       k8s.vm.box = "ubuntu/xenial64"
       k8s.ssh.insert_key = false
       k8s.vm.provision "shell", path: "./up_sh/init_environment.sh"
       k8s.vm.provision "shell", path: "./up_sh/install_docker_ce.sh"
       k8s.vm.provision "shell", path: "./up_sh/install_k8s.sh"
       k8s.vm.provider "virtualbox" do |v|
          v.name = "base-k8s-ubuntu"
          v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
       end
   end
end